export const MAP_KEY = 'AIzaSyB1OLauMwO5CCMQg0gZejZjm0q1lAEQFSo';

export const CLI_ID = 'VRJROPCAFPLE2AGGH02TVCWP5TYRO4UMQKCYSROZGYZER20V';
export const CLI_SECRET = 'C5CQZGWYOVGO0SNA5IXYJVLMA44AMBX4BFSLVAQQLDUMLOGA';
